### ISSUE TITLE
License undecided

### ISSUE THREAD

**Issue by JayFoxRox** [JayFoxRox/thps2-tools#1]
I only didn't add a license because the release was a bit rushed.

I'm fine with GPL, BSD or MIT probably.
Please leave a comment if you want to use the code so I can add a proper license.

**Comment by Calinou** [comment]
Hi, could you add the MIT license please? I don't personally plan on using this right now, but it'd be good to make the license clear as soon as possible.

**Comment by JayFoxRox** [comment]
Closed in e78065aa8ac54e21d1479cf4832d8edc88fd8392
